name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
 - name: 清理旧编译缓存
        run: flutter clean
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.8'

      - name: Config Flutter mirror
        run: |
          echo "PUB_HOSTED_URL=https://pub.flutter-io.cn" >> $env:GITHUB_ENV
          echo "FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn" >> $env:GITHUB_ENV

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: App-APK
          path: build/app/outputs/flutter-apk/app-release.apk
